### ISSUE TITLE
[Bug - 1.19.2] Incompatible with "ITLT" (It's the little things)

### ISSUE THREAD

**Issue by KuryKat** [kitUIN/ChatImage#17]
### Bug 描述

Unable to launch the game when using ChatImage + It's the Little things because both export the same package...

### 复现问题的步骤

```plain text
1. Install Minecraft + Forge 43.2.23
2. Install ChatImage 1.1.6
3. Install ITLT (It's the little things) 2.2.0 
4. Try to Launch the Game
5. Exception caught from launcher (check below for the logs)
```

### 日志记录

```
Exception caught from launcher
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:58)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.module.ResolutionException: Modules itlt and chatimage export package net.sf.image4j.util to module forge
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
```

### Mod版本

ChatImage 1.1.6 - Minecraft 1.19.2

### 电脑系统|JAVA版本

Windows 10 + JAVA 17

![image](https://github.com/kitUIN/ChatImage/assets/57152799/47e650b6-8e39-43d9-90b2-664c6f9297de)

![image](https://github.com/kitUIN/ChatImage/assets/57152799/dee459fd-c53b-4842-88ea-7351773b7eaf)

![image](https://github.com/kitUIN/ChatImage/assets/57152799/b9bf7fe1-a511-419a-b7d7-550934060d4f)

### 截图

![image](https://github.com/kitUIN/ChatImage/assets/57152799/99b1f456-ee58-4c84-96f2-50468dce84fc)

### 备注

Maybe [this](https://nipafx.dev/java-9-migration-guide/#split-packages) or [this](https://stackoverflow.com/questions/46277188/modules-a-and-b-export-package-some-package-to-module-c-in-java-9) could help?

**Comment by kitUIN** [comment]
`ITLT`  that have the same module patch as `ChatImage`. It's unfixable. You can only delete the mods that have the same module.

**Comment by kitUIN** [comment]
You can easily fix it by opening the `ChatImage` jar file and delete the folder `net.sf.image4j`

**Comment by KuryKat** [comment]
I can't do such a thing, since I am distributing the mods in my modpack, there's not a way for me to edit the jar and then release it with the modpack, and that could break some licenses even if I could 😅😅

**Comment by kitUIN** [comment]
Unfortunately, I haven't found another way to fix the bug yet

**Comment by KuryKat** [comment]
@kitUIN do you think it could be possible to fix this with JarJar?

https://forge.gemwire.uk/wiki/Jar-in-Jar

**Comment by KuryKat** [comment]
I managed to fix the issue on ITLT's side, by relocating the package to somewhere else using the shadow plugin, do you think you could do the same on your mod? 

I did some PRs [here](https://github.com/zlepper/itlt/pull/46) for the other mod, maybe you could take a look, that fixed the issue

**Comment by kitUIN** [comment]
you are right🤗
I will fix it

**Comment by KuryKat** [comment]
Thank you! ❤🙌
